import { useState } from "react";
import { useReports } from "../hooks/useComply";
import StatsCard from "../components/StatsCard";
import DataTable from "../components/DataTable";
import FilterBar from "../components/FilterBar";
import StatusBadge from "../components/StatusBadge";
import { formatDate } from "../utils/helpers";
import { FileText, BarChart3, TrendingUp, Shield, FileSpreadsheet, Download, Eye, FileDown } from "lucide-react";

export default function Reports() {
  const { data: reports, summary, loading } = useReports();
  const [search, setSearch] = useState("");
  const [filters, setFilters] = useState({ type: "", status: "", format: "" });
  const [selectedReport, setSelectedReport] = useState(null);

  const updateFilter = (key, value) => setFilters(prev => ({ ...prev, [key]: value }));

  const filtered = (reports || []).filter(r => {
    if (search && !r.title.toLowerCase().includes(search.toLowerCase()) && !r.framework.toLowerCase().includes(search.toLowerCase())) return false;
    if (filters.type && r.type !== filters.type) return false;
    if (filters.status && r.status !== filters.status) return false;
    if (filters.format && r.format !== filters.format) return false;
    return true;
  });

  if (loading) return <div className="p-6 text-gray-500">Loading reports...</div>;

  const filterConfig = [
    { key: "type", placeholder: "All Types", value: filters.type, options: [
      { value: "compliance_summary", label: "Compliance Summary" }, { value: "risk_analysis", label: "Risk Analysis" },
      { value: "audit_findings", label: "Audit Findings" }, { value: "incident_trends", label: "Incident Trends" },
      { value: "policy_compliance", label: "Policy Compliance" }, { value: "executive_pack", label: "Executive Pack" },
    ]},
    { key: "status", placeholder: "All Statuses", value: filters.status, options: [
      { value: "completed", label: "Completed" }, { value: "pending", label: "Pending" },
    ]},
    { key: "format", placeholder: "All Formats", value: filters.format, options: [
      { value: "pdf", label: "PDF" }, { value: "excel", label: "Excel" }, { value: "csv", label: "CSV" },
    ]},
  ];

  const typeIcon = (type) => {
    switch (type) {
      case "compliance_summary": return <Shield className="w-4 h-4" />;
      case "risk_analysis": return <TrendingUp className="w-4 h-4" />;
      case "audit_findings": return <BarChart3 className="w-4 h-4" />;
      case "incident_trends": return <BarChart3 className="w-4 h-4" />;
      case "policy_compliance": return <FileText className="w-4 h-4" />;
      case "executive_pack": return <FileSpreadsheet className="w-4 h-4" />;
      default: return <FileText className="w-4 h-4" />;
    }
  };

  if (selectedReport) {
    return (
      <div className="space-y-6 max-w-4xl">
        <button onClick={() => setSelectedReport(null)} className="text-sm text-gray-500 hover:text-gray-700 flex items-center gap-1">← Back to Reports</button>
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-start justify-between mb-4">
            <div>
              <StatusBadge status={selectedReport.type} />
              <h2 className="text-lg font-bold text-gray-900 mt-1">{selectedReport.title}</h2>
              <p className="text-sm text-gray-500 mt-1">{selectedReport.description}</p>
            </div>
          </div>
          <div className="grid gap-4 sm:grid-cols-3 mb-4">
            <div className="bg-gray-50 rounded-lg p-3">
              <p className="text-xs text-gray-500">Framework</p>
              <p className="text-sm font-medium text-gray-900">{selectedReport.framework}</p>
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <p className="text-xs text-gray-500">Format</p>
              <p className="text-sm font-medium text-gray-900 uppercase">{selectedReport.format}</p>
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <p className="text-xs text-gray-500">Pages</p>
              <p className="text-sm font-medium text-gray-900">{selectedReport.pages}</p>
            </div>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 mb-4">
            <div className="bg-gray-50 rounded-lg p-3">
              <p className="text-xs text-gray-500">Generated By</p>
              <p className="text-sm font-medium text-gray-900">{selectedReport.generatedBy}</p>
            </div>
            <div className="bg-gray-50 rounded-lg p-3">
              <p className="text-xs text-gray-500">Generated Date</p>
              <p className="text-sm font-medium text-gray-900">{formatDate(selectedReport.generatedDate)}</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-600 text-white rounded-lg text-sm font-medium hover:bg-emerald-700 transition-colors">
              <Download className="w-4 h-4" /> Download {selectedReport.format.toUpperCase()}
            </button>
            <button className="inline-flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors">
              <Eye className="w-4 h-4" /> Preview
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
        <p className="text-sm text-gray-500 mt-1">Generate, view, and export compliance and risk reports</p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatsCard title="Total Reports" value={summary?.total || 20} icon={FileText} />
        <StatsCard title="Compliance Summary" value={summary?.byType?.compliance_summary || 0} icon={Shield} />
        <StatsCard title="Risk Analysis" value={summary?.byType?.risk_analysis || 0} icon={TrendingUp} />
        <StatsCard title="Executive Packs" value={summary?.byType?.executive_pack || 0} icon={FileSpreadsheet} trend="up" change={25} />
      </div>

      <FilterBar search={search} onSearchChange={setSearch} filters={filterConfig} onFilterChange={updateFilter} />

      <div className="bg-white rounded-xl border border-gray-200">
        <DataTable
          columns={[
            { key: "type", label: "Type", render: (v) => (
              <div className="flex items-center gap-2">
                <div className="p-1.5 bg-gray-50 rounded text-gray-400">{typeIcon(v)}</div>
                <StatusBadge status={v} />
              </div>
            )},
            { key: "title", label: "Report", render: (v) => <span className="font-medium text-gray-900">{v}</span> },
            { key: "framework", label: "Framework" },
            { key: "generatedBy", label: "Generated By" },
            { key: "generatedDate", label: "Date", render: (v) => formatDate(v) },
            { key: "format", label: "Format", render: (v) => <span className="uppercase text-xs font-mono font-medium text-gray-600">{v}</span> },
            { key: "pages", label: "Pages" },
            { key: "status", label: "Status", render: (v) => <StatusBadge status={v} /> },
            { key: "actions", label: "", render: (_, row) => (
              <div className="flex items-center gap-1">
                <button onClick={(e) => { e.stopPropagation(); setSelectedReport(row); }} className="p-1.5 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded" title="View"><Eye className="w-4 h-4" /></button>
                <button onClick={(e) => e.stopPropagation()} className="p-1.5 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded" title="Download"><FileDown className="w-4 h-4" /></button>
              </div>
            )},
          ]}
          onRowClick={(row) => setSelectedReport(row)}
          data={filtered}
        />
      </div>
    </div>
  );
}
