export function getWorkforcePlans() {
  return [
    { id: 1, title: "Engineering Growth Q2", department: "Engineering", year: 2025, headcount: 320, targetHeadcount: 350, budget: 4800000, status: "active", description: "Scale engineering team for new product lines", createdBy: "Sarah Chen", createdDate: "2025-01-15", notes: "Focus on senior hires" },
    { id: 2, title: "Sales Team Expansion", department: "Sales", year: 2025, headcount: 210, targetHeadcount: 250, budget: 4200000, status: "active", description: "Expand sales team across new regions", createdBy: "Mike Ross", createdDate: "2025-02-01", notes: "EMEA region priority" },
    { id: 3, title: "Marketing Restructure", department: "Marketing", year: 2025, headcount: 62, targetHeadcount: 55, budget: 1100000, status: "planned", description: "Optimize marketing team structure", createdBy: "Lisa Park", createdDate: "2025-02-20", notes: "Pending budget approval" },
    { id: 4, title: "Product Q3 Hiring", department: "Product", year: 2025, headcount: 85, targetHeadcount: 100, budget: 1700000, status: "draft", description: "Hire product managers and analysts", createdBy: "David Kim", createdDate: "2025-03-01", notes: "Drafting reqs" },
    { id: 5, title: "Design Team Growth", department: "Design", year: 2025, headcount: 45, targetHeadcount: 55, budget: 900000, status: "active", description: "Strengthen design capabilities", createdBy: "Anna Liu", createdDate: "2025-01-10", notes: "UX research focus" },
    { id: 6, title: "HR Transformation", department: "HR", year: 2025, headcount: 28, targetHeadcount: 32, budget: 560000, status: "on_hold", description: "HR digital transformation hiring", createdBy: "James Wong", createdDate: "2025-02-15", notes: "On hold pending budget review" },
    { id: 7, title: "Finance Year-End", department: "Finance", year: 2025, headcount: 35, targetHeadcount: 38, budget: 700000, status: "planned", description: "Year-end financial planning hires", createdBy: "Rachel Green", createdDate: "2025-03-10", notes: "Q4 start" },
    { id: 8, title: "Operations Efficiency", department: "Operations", year: 2025, headcount: 55, targetHeadcount: 60, budget: 880000, status: "active", description: "Improve operational efficiency", createdBy: "Tom Hardy", createdDate: "2025-01-20", notes: "" },
    { id: 9, title: "Engineering Interns", department: "Engineering", year: 2026, headcount: 12, targetHeadcount: 20, budget: 240000, status: "draft", description: "Summer internship program", createdBy: "Sarah Chen", createdDate: "2025-03-15", notes: "Planning for 2026" },
    { id: 10, title: "Data Science Team", department: "Engineering", year: 2025, headcount: 18, targetHeadcount: 25, budget: 1700000, status: "planned", description: "Build out data science capability", createdBy: "Nina Patel", createdDate: "2025-02-28", notes: "AI/ML focus" },
  ];
}
