export function getCalendarEvents() {
  return [
    { id: 1, title: "Q2 Financial Audit - Closing Meeting", type: "audit", date: "2026-06-28", endDate: "2026-06-28", status: "active", owner: "Sarah Chen", description: "Closing meeting for Q2 2026 internal financial audit." },
    { id: 2, title: "SOC 2 Readiness - Controls Testing", type: "audit", date: "2026-07-15", endDate: "2026-07-19", status: "active", owner: "Compliance Director", description: "Week-long controls testing phase for SOC 2 Type II readiness." },
    { id: 3, title: "ISO 27001 Surveillance Audit", type: "audit", date: "2026-06-30", endDate: "2026-07-05", status: "active", owner: "Mike Johnson", description: "ISO 27001 annual surveillance audit by certification body." },
    { id: 4, title: "GDPR Annual Report Submission", type: "filing", date: "2026-07-15", endDate: "2026-07-15", status: "pending", owner: "DPO", description: "Deadline for GDPR annual data protection report submission." },
    { id: 5, title: "PCI DSS Quarterly ASV Scan", type: "filing", date: "2026-07-01", endDate: "2026-07-07", status: "pending", owner: "Security Engineer", description: "Quarterly external vulnerability scan by approved scanning vendor." },
    { id: 6, title: "Information Security Policy Review", type: "review", date: "2026-08-15", endDate: "2026-08-19", status: "pending", owner: "CISO", description: "Annual review of Information Security Policy." },
    { id: 7, title: "Data Protection Policy Review", type: "review", date: "2026-07-01", endDate: "2026-07-03", status: "overdue", owner: "DPO", description: "Annual review of Data Protection Policy." },
    { id: 8, title: "Acceptable Use Policy Review", type: "review", date: "2026-06-30", endDate: "2026-07-02", status: "overdue", owner: "IT Director", description: "Annual review of Acceptable Use Policy." },
    { id: 9, title: "GDPR Cross-Border Transfer Deadline", type: "filing", date: "2026-09-15", endDate: "2026-09-15", status: "pending", owner: "DPO", description: "Deadline for cross-border data transfer assessment completion." },
    { id: 10, title: "Code of Conduct Renewal", type: "review", date: "2026-09-01", endDate: "2026-09-05", status: "pending", owner: "General Counsel", description: "Biennial review and renewal of Code of Conduct." },
    { id: 11, title: "SOX 404 Q3 Testing", type: "audit", date: "2026-08-01", endDate: "2026-09-15", status: "pending", owner: "Internal Audit", description: "Q3 2026 SOX 404 internal control testing." },
    { id: 12, title: "HIPAA Privacy Assessment", type: "audit", date: "2026-07-15", endDate: "2026-08-30", status: "pending", owner: "Privacy Officer", description: "Annual HIPAA privacy and security assessment." },
    { id: 13, title: "SEC Cybersecurity Disclosure Filing", type: "filing", date: "2026-08-01", endDate: "2026-08-01", status: "pending", owner: "General Counsel", description: "Annual SEC cybersecurity risk management and incident disclosure filing." },
    { id: 14, title: "PCI DSS Report on Compliance", type: "filing", date: "2026-07-31", endDate: "2026-07-31", status: "pending", owner: "Compliance Analyst", description: "PCI DSS ROC submission deadline." },
    { id: 15, title: "Annual Ethics Training Completion", type: "deadline", date: "2026-08-30", endDate: "2026-08-30", status: "pending", owner: "HR Director", description: "All employees must complete annual ethics and compliance training." },
    { id: 16, title: "Board Risk Appetite Review", type: "review", date: "2026-08-30", endDate: "2026-08-31", status: "pending", owner: "Board Risk Committee", description: "Annual board review and approval of risk appetite statement." },
    { id: 17, title: "CMMC Assessment", type: "audit", date: "2026-10-01", endDate: "2026-10-05", status: "pending", owner: "CISO", description: "CMMC Level 2 certification assessment." },
    { id: 18, title: "DORA Compliance Deadline", type: "filing", date: "2026-09-30", endDate: "2026-09-30", status: "pending", owner: "CRO", description: "EU Digital Operational Resilience Act compliance deadline." },
    { id: 19, title: "Conflict of Interest Disclosures Due", type: "deadline", date: "2026-08-01", endDate: "2026-08-01", status: "pending", owner: "Legal", description: "Annual conflict of interest disclosure submission deadline for all officers and directors." },
    { id: 20, title: "Quarterly Access Review", type: "deadline", date: "2026-07-05", endDate: "2026-07-12", status: "active", owner: "IT Security", description: "Quarterly privileged access review." },
    { id: 21, title: "Vendor Risk Assessment Q3", type: "review", date: "2026-09-01", endDate: "2026-09-30", status: "pending", owner: "Risk Manager", description: "Q3 2026 annual vendor risk assessments for critical vendors." },
    { id: 22, title: "EU AI Act Classification Report", type: "filing", date: "2026-10-01", endDate: "2026-10-01", status: "pending", owner: "AI Governance Lead", description: "Submit AI system risk classifications per EU AI Act." },
    { id: 23, title: "Cyber Insurance Renewal", type: "deadline", date: "2026-08-01", endDate: "2026-08-01", status: "active", owner: "Risk Manager", description: "Annual cyber insurance policy renewal." },
    { id: 24, title: "Penetration Test - External", type: "audit", date: "2026-08-01", endDate: "2026-08-15", status: "pending", owner: "Security Operations", description: "Annual external infrastructure penetration test." },
    { id: 25, title: "Data Retention Audit", type: "audit", date: "2026-07-15", endDate: "2026-07-26", status: "active", owner: "Records Manager", description: "Audit of data retention and disposal practices across all departments." },
    { id: 26, title: "BCP Tabletop Exercise", type: "audit", date: "2026-07-30", endDate: "2026-07-30", status: "pending", owner: "BCM Director", description: "Semi-annual business continuity tabletop exercise." },
    { id: 27, title: "SOX 302 CEO/CFO Certification", type: "filing", date: "2026-07-15", endDate: "2026-07-15", status: "active", owner: "CFO", description: "Quarterly SOX 302 certification of internal controls." },
    { id: 28, title: "GDPR DSAR Processing Review", type: "review", date: "2026-07-10", endDate: "2026-07-12", status: "active", owner: "DPO", description: "Monthly review of DSAR processing timeliness and quality." },
    { id: 29, title: "Cloud Security Posture Review", type: "review", date: "2026-07-10", endDate: "2026-08-10", status: "pending", owner: "Cloud Security Architect", description: "Review of cloud security posture across all cloud providers." },
    { id: 30, title: "Privacy Impact Assessment Backlog", type: "deadline", date: "2026-08-01", endDate: "2026-08-01", status: "pending", owner: "DPO", description: "Clear backlog of pending privacy impact assessments." },
    { id: 31, title: "UK GDPR Rep Appointment", type: "filing", date: "2026-07-15", endDate: "2026-07-15", status: "active", owner: "DPO", description: "Designate UK GDPR representative." },
    { id: 32, title: "ISO 27001 Internal Audit Program", type: "audit", date: "2026-08-01", endDate: "2026-08-15", status: "pending", owner: "Quality Manager", description: "Annual ISO 27001 internal audit program." },
    { id: 33, title: "FCPA Risk Assessment", type: "review", date: "2026-09-15", endDate: "2026-09-30", status: "pending", owner: "Legal Counsel", description: "Annual FCPA risk assessment for high-risk markets." },
    { id: 34, title: "Corporate Transparency Act Filing", type: "filing", date: "2026-09-01", endDate: "2026-09-01", status: "pending", owner: "Corporate Secretary", description: "FinCEN beneficial ownership information report." },
    { id: 35, title: "Quarterly Security Awareness Metrics", type: "deadline", date: "2026-07-05", endDate: "2026-07-05", status: "active", owner: "Security Awareness", description: "Q2 2026 security awareness metrics report due." },
    { id: 36, title: "Tokenization Implementation Review", type: "review", date: "2026-08-20", endDate: "2026-08-22", status: "pending", owner: "Security Architect", description: "Review of payment tokenization implementation status." },
    { id: 37, title: "Data Processing Agreement Renewals", type: "deadline", date: "2026-08-15", endDate: "2026-08-15", status: "pending", owner: "Legal Counsel", description: "DPA renewals with all sub-processors." },
    { id: 38, title: "Social Engineering Testing", type: "audit", date: "2026-07-15", endDate: "2026-07-19", status: "active", owner: "Security Awareness", description: "Quarterly phishing and social engineering simulation." },
    { id: 39, title: "GLBA Compliance Review", type: "review", date: "2026-09-01", endDate: "2026-09-05", status: "pending", owner: "Privacy Officer", description: "Annual GLBA privacy compliance review." },
    { id: 40, title: "NIST CSF Assessment", type: "review", date: "2026-08-20", endDate: "2026-08-31", status: "pending", owner: "IT Risk Manager", description: "Annual NIST Cybersecurity Framework assessment." },
    { id: 41, title: "Data Erasure Request Queue Clearance", type: "deadline", date: "2026-07-02", endDate: "2026-07-02", status: "overdue", owner: "DPO", description: "Clear pending right-to-erasure request backlog." },
    { id: 42, title: "SEC Whistleblower Program Review", type: "review", date: "2026-08-01", endDate: "2026-08-03", status: "pending", owner: "General Counsel", description: "Annual review of whistleblower program compliance." },
    { id: 43, title: "BIometric Privacy Compliance (BIPA)", type: "filing", date: "2026-09-01", endDate: "2026-09-01", status: "pending", owner: "Privacy Counsel", description: "Illinois BIPA compliance documentation deadline." },
    { id: 44, title: "Patent Filing - Zero-Trust Technology", type: "deadline", date: "2026-07-15", endDate: "2026-07-15", status: "active", owner: "IP Counsel", description: "Provisional patent application deadline." },
    { id: 45, title: "Cookie Consent Mechanism Update", type: "deadline", date: "2026-07-01", endDate: "2026-07-01", status: "overdue", owner: "Digital Marketing", description: "Update cookie consent mechanism per ePrivacy Directive." },
    { id: 46, title: "Anti-Bribery & Corruption Audit - EY", type: "audit", date: "2026-06-15", endDate: "2026-07-30", status: "active", owner: "Legal Team", description: "FCPA compliance audit by EY Forensics." },
    { id: 47, title: "Sustainability Report (TCFD)", type: "filing", date: "2026-09-30", endDate: "2026-09-30", status: "pending", owner: "Sustainability Officer", description: "TCFD-aligned climate risk disclosure report." },
    { id: 48, title: "AI Ethics Board Meeting", type: "review", date: "2026-07-20", endDate: "2026-07-20", status: "pending", owner: "AI Ethics Board", description: "Quarterly AI Ethics Board meeting." },
    { id: 49, title: "Key Risk Indicator Review", type: "review", date: "2026-08-15", endDate: "2026-08-16", status: "pending", owner: "Risk Analytics", description: "Annual KRI recalibration and threshold review." },
    { id: 50, title: "Internal Controls over Financial Reporting", type: "audit", date: "2026-08-01", endDate: "2026-09-15", status: "pending", owner: "Internal Audit", description: "SOX 404 Q3 testing cycle." },
  ];
}

export function getCalendarSummary() {
  const events = getCalendarEvents();
  return {
    total: events.length,
    byType: {
      audit: events.filter(e => e.type === "audit").length,
      filing: events.filter(e => e.type === "filing").length,
      review: events.filter(e => e.type === "review").length,
      deadline: events.filter(e => e.type === "deadline").length,
    },
    byMonth: [
      { month: "Jun 2026", count: events.filter(e => e.date >= "2026-06-01" && e.date <= "2026-06-30").length },
      { month: "Jul 2026", count: events.filter(e => e.date >= "2026-07-01" && e.date <= "2026-07-31").length },
      { month: "Aug 2026", count: events.filter(e => e.date >= "2026-08-01" && e.date <= "2026-08-31").length },
      { month: "Sep 2026", count: events.filter(e => e.date >= "2026-09-01" && e.date <= "2026-09-30").length },
      { month: "Oct 2026", count: events.filter(e => e.date >= "2026-10-01" && e.date <= "2026-10-31").length },
    ],
    upcoming: events.filter(e => e.date >= "2026-06-16" && e.date <= "2026-07-15").length,
    overdue: events.filter(e => e.status === "overdue").length,
  };
}
