export function getComplianceDashboard() {
  return {
    complianceHealthScore: 78,
    complianceScoreTrend: [
      { month: "Jan", score: 72 },
      { month: "Feb", score: 74 },
      { month: "Mar", score: 73 },
      { month: "Apr", score: 76 },
      { month: "May", score: 75 },
      { month: "Jun", score: 78 },
    ],
    stats: {
      openRisks: 23,
      criticalRisks: 4,
      activeAudits: 6,
      outstandingFindings: 14,
      policyCompliance: 87,
      obligationsDueSoon: 12,
      evidenceCoverage: 79,
    },
    riskDistribution: [
      { name: "Critical", value: 4, color: "#ef4444" },
      { name: "High", value: 8, color: "#f97316" },
      { name: "Medium", value: 11, color: "#eab308" },
      { name: "Low", value: 9, color: "#22c55e" },
    ],
    auditStatus: [
      { name: "Planning", value: 3, color: "#6b7280" },
      { name: "Active", value: 6, color: "#3b82f6" },
      { name: "Review", value: 4, color: "#eab308" },
      { name: "Closed", value: 7, color: "#22c55e" },
    ],
    incidentTrend: [
      { month: "Jan", reported: 5, resolved: 3 },
      { month: "Feb", reported: 4, resolved: 4 },
      { month: "Mar", reported: 7, resolved: 5 },
      { month: "Apr", reported: 3, resolved: 6 },
      { month: "May", reported: 6, resolved: 4 },
      { month: "Jun", reported: 4, resolved: 5 },
    ],
    recentObligations: [
      { id: 1, title: "GDPR Annual Report Filing", category: "regulatory", owner: "Legal Team", dueDate: "2026-07-15", riskLevel: "high", status: "active" },
      { id: 2, title: "SOC 2 Type II Audit", category: "regulatory", owner: "Compliance Team", dueDate: "2026-08-01", riskLevel: "critical", status: "active" },
      { id: 3, title: "ISO 27001 Surveillance", category: "industry", owner: "IT Security", dueDate: "2026-06-30", riskLevel: "high", status: "pending" },
      { id: 4, title: "Data Breach Notification", category: "legal", owner: "DPO", dueDate: "2026-06-20", riskLevel: "critical", status: "overdue" },
      { id: 5, title: "Vendor Risk Assessment", category: "contractual", owner: "Procurement", dueDate: "2026-07-10", riskLevel: "medium", status: "active" },
      { id: 6, title: "PCI DSS Quarterly Scan", category: "industry", owner: "IT Security", dueDate: "2026-07-01", riskLevel: "high", status: "pending" },
      { id: 7, title: "Annual AML Compliance Review", category: "regulatory", owner: "Compliance Officer", dueDate: "2026-08-15", riskLevel: "medium", status: "pending" },
      { id: 8, title: "HIPAA Privacy Assessment", category: "regulatory", owner: "Privacy Officer", dueDate: "2026-06-25", riskLevel: "high", status: "overdue" },
    ],
    topRisks: [
      { id: 1, title: "Data center single point of failure", probability: 4, impact: 5, score: 20, owner: "IT Director", status: "mitigating" },
      { id: 2, title: "GDPR non-compliance penalties", probability: 3, impact: 5, score: 15, owner: "DPO", status: "mitigating" },
      { id: 3, title: "Third-party vendor data breach", probability: 4, impact: 4, score: 16, owner: "Procurement", status: "identified" },
      { id: 4, title: "Insider threat - privileged access", probability: 3, impact: 4, score: 12, owner: "IT Security", status: "assessed" },
      { id: 5, title: "System availability SLA breach", probability: 3, impact: 3, score: 9, owner: "Operations", status: "mitigating" },
    ],
    activeAudits: [
      { id: 1, title: "Q2 2026 Internal Financial Audit", type: "internal", lead: "Sarah Chen", startDate: "2026-06-01", endDate: "2026-06-28", status: "active", progress: 65 },
      { id: 2, title: "SOC 2 Type II Readiness", type: "external", lead: "Deloitte", startDate: "2026-05-15", endDate: "2026-07-30", status: "active", progress: 40 },
      { id: 3, title: "ISO 27001 Internal Audit", type: "internal", lead: "Mike Johnson", startDate: "2026-06-10", endDate: "2026-07-05", status: "active", progress: 30 },
      { id: 4, title: "PCI DSS Compliance Review", type: "regulatory", lead: "QSA Assessor", startDate: "2026-06-15", endDate: "2026-08-01", status: "active", progress: 25 },
      { id: 5, title: "Vendor Security Assessment", type: "external", lead: "SecurityScorecard", startDate: "2026-06-05", endDate: "2026-07-15", status: "active", progress: 50 },
    ],
    recentIncidents: [
      { id: 1, title: "Unauthorized access attempt - production DB", severity: "critical", status: "investigating", reportedDate: "2026-06-14", assignee: "IT Security" },
      { id: 2, title: "Phishing campaign detected", severity: "high", status: "remediation", reportedDate: "2026-06-12", assignee: "Security Team" },
      { id: 3, title: "Sensitive data exposed in log files", severity: "high", status: "resolved", reportedDate: "2026-06-10", assignee: "DevOps" },
      { id: 4, title: "Policy violation - personal device usage", severity: "medium", status: "closed", reportedDate: "2026-06-08", assignee: "HR" },
      { id: 5, title: "Firewall misconfiguration", severity: "critical", status: "resolved", reportedDate: "2026-06-05", assignee: "Network Team" },
    ],
  };
}
