export function getIncidents() {
  const now = new Date();
  const daysAgo = (d) => {
    const date = new Date(now);
    date.setDate(date.getDate() - d);
    return date.toISOString().split("T")[0];
  };

  return [
    { id: 1, title: "Unauthorized access attempt - production database", severity: "critical", status: "investigating", reportedDate: daysAgo(2), assignee: "IT Security", reportedBy: "SOC Analyst", category: "unauthorized_access", description: "Multiple failed login attempts detected on production database from external IP address. Investigation ongoing to determine if any data was accessed.", rootCause: "", resolution: "" },
    { id: 2, title: "Phishing campaign targeting finance department", severity: "high", status: "remediation", reportedDate: daysAgo(4), assignee: "Security Team", reportedBy: "Employee Report", category: "phishing", description: "Sophisticated phishing emails targeting finance team members with fake invoice payment requests. 3 employees clicked the link.", rootCause: "Targeted phishing campaign bypassing email filters through compromised legitimate sender domain.", resolution: "Email filters updated, affected accounts reset, awareness training conducted" },
    { id: 3, title: "Sensitive data exposed in application logs", severity: "high", status: "resolved", reportedDate: daysAgo(6), assignee: "DevOps", reportedBy: "Security Scan", category: "data_leakage", description: "Customer PII including email addresses and partial credit card numbers found in application debug logs accessible to engineering team.", rootCause: "Logging configuration set to debug mode in production, capturing sensitive request data.", resolution: "Logging configuration fixed, log entries purged, access reviewed" },
    { id: 4, title: "Policy violation - personal device usage", severity: "medium", status: "closed", reportedDate: daysAgo(8), assignee: "HR", reportedBy: "Manager Report", category: "policy_violation", description: "Employee found using personal unencrypted laptop to access company data in violation of Remote Work and Acceptable Use policies.", rootCause: "Employee unaware of policy requirements for remote access.", resolution: "Employee counseled, device enrolled in MDM, policy awareness training completed" },
    { id: 5, title: "Firewall misconfiguration exposes internal services", severity: "critical", status: "resolved", reportedDate: daysAgo(11), assignee: "Network Team", reportedBy: "Automated Scan", category: "misconfiguration", description: "Internal admin panel exposed to internet due to incorrect firewall rule after maintenance change. Exposed for approximately 4 hours.", rootCause: "Firewall rule change during scheduled maintenance incorrectly allowed public access to management interface.", resolution: "Rule corrected, access logs reviewed (no unauthorized access detected), change management process updated" },
    { id: 6, title: "Malware detected on workstation", severity: "high", status: "resolved", reportedDate: daysAgo(14), assignee: "IT Support", reportedBy: "Endpoint Protection", category: "malware", description: "EDR alert detected potentially unwanted application (PUA) on marketing department workstation. Application quarantined automatically.", rootCause: "Employee downloaded software from untrusted source for a project.", resolution: "Workstation scanned and cleaned, user counseled on software installation policy" },
    { id: 7, title: "Lost company laptop", severity: "high", status: "resolved", reportedDate: daysAgo(17), assignee: "IT Security", reportedBy: "Employee Report", category: "lost_device", description: "Employee reported company-issued laptop lost during business travel. Device encrypted with BitLocker and reportedly password protected.", rootCause: "Personal negligence during travel.", resolution: "Device location attempted via MDM (offline), BitLocker keys verified secure, remote wipe initiated, replacement issued" },
    { id: 8, title: "Social engineering - help desk password reset", severity: "high", status: "remediation", reportedDate: daysAgo(5), assignee: "IT Service Desk", reportedBy: "Internal Audit", category: "social_engineering", description: "Help desk technician reset password for attacker posing as executive via phone call. Attacker gained access to email for 30 minutes.", rootCause: "Help desk verification procedure not followed; caller ID spoofing used.", resolution: "Password reset procedures updated, additional verification steps implemented, affected accounts audited" },
    { id: 9, title: "Cloud storage bucket publicly accessible", severity: "critical", status: "resolved", reportedDate: daysAgo(20), assignee: "CloudOps", reportedBy: "Security Scan", category: "misconfiguration", description: "AWS S3 bucket containing backup data was configured as publicly readable. Discovered during routine cloud security scan. No evidence of data access.", rootCause: "Terraform template misconfiguration - missing private ACL setting.", resolution: "Bucket access restricted, Terraform templates updated and reviewed, cloud security scanning enhanced" },
    { id: 10, title: "GDPR data subject erasure request missed deadline", severity: "medium", status: "remediation", reportedDate: daysAgo(9), assignee: "DPO", reportedBy: "Compliance Team", category: "compliance_failure", description: "Data subject erasure request exceeded 30-day statutory deadline due to processing backlog in engineering team.", rootCause: "Lack of automated erasure workflow and insufficient engineering capacity for manual data deletion.", resolution: "Request processed late, automated erasure workflow being implemented, backlog triaged" },
    { id: 11, title: "Vendor data breach notification", severity: "critical", status: "investigating", reportedDate: daysAgo(1), assignee: "Procurement", reportedBy: "Vendor Notification", category: "third_party", description: "Critical vendor (cloud infrastructure provider) reported security incident potentially affecting customer data hosted on their platform.", rootCause: "", resolution: "" },
    { id: 12, title: "Unauthorized physical access attempt", severity: "medium", status: "closed", reportedDate: daysAgo(25), assignee: "Physical Security", reportedBy: "Security Guard", category: "physical_security", description: "Individual without valid badge attempted to tailgate into secured office area. Stopped by security personnel.", rootCause: "Tailgating - individual followed authorized employee through access door.", resolution: "Incident documented, security awareness reminder sent to all employees" },
    { id: 13, title: "API rate limit abuse detected", severity: "medium", status: "resolved", reportedDate: daysAgo(22), assignee: "API Team", reportedBy: "Automated Monitoring", category: "abuse", description: "Customer API key used to make excessive requests (1000x normal rate) potentially indicating account compromise or abuse.", rootCause: "Customer API key leaked in public GitHub repository.", resolution: "API key rotated, customer notified, GitHub repository scanned and secret removed" },
    { id: 14, title: "Ransomware attempt blocked", severity: "critical", status: "resolved", reportedDate: daysAgo(16), assignee: "SOC", reportedBy: "EDR Alert", category: "ransomware", description: "EDR detected and blocked ransomware encryption attempt on engineering workstation. Attack originated from malicious email attachment.", rootCause: "Employee opened phishing email containing malicious macro-enabled document.", resolution: "Threat contained by EDR, workstation isolated and reimaged, IOC shared with threat intelligence" },
    { id: 15, title: "Data export by departing employee", severity: "high", status: "investigating", reportedDate: daysAgo(3), assignee: "IT Security", reportedBy: "DLP Alert", category: "data_exfiltration", description: "DLP system detected departing employee downloading large volume of customer data to personal USB drive on last day of employment.", rootCause: "", resolution: "" },
    { id: 16, title: "Insider trading policy breach investigation", severity: "high", status: "investigating", reportedDate: daysAgo(7), assignee: "Legal Counsel", reportedBy: "Compliance Officer", category: "policy_violation", description: "Executive reported stock trades during blackout period. Referral to legal for investigation.", rootCause: "", resolution: "" },
    { id: 17, title: "Incorrect data processing consent", severity: "medium", status: "resolved", reportedDate: daysAgo(30), assignee: "Privacy Team", reportedBy: "Audit Finding", category: "compliance_failure", description: "Marketing automation platform found processing personal data without proper consent for 2,500 contacts.", rootCause: "Legacy consent records not migrated to new consent management platform.", resolution: "Consent re-obtained for affected contacts, data migration audit completed, records corrected" },
    { id: 18, title: "Privileged access account compromise", severity: "critical", status: "remediation", reportedDate: daysAgo(10), assignee: "IAM Team", reportedBy: "SIEM Alert", category: "account_compromise", description: "Service account with admin privileges showed unusual login pattern from unrecognized geographic location.", rootCause: "Service account credentials found in public code repository.", resolution: "Account disabled, credentials rotated, access logs being analyzed for unauthorized activity" },
    { id: 19, title: "Software license compliance gap", severity: "low", status: "closed", reportedDate: daysAgo(35), assignee: "IT Procurement", reportedBy: "Software Audit", category: "compliance_failure", description: "Software license audit revealed 50 unlicensed copies of analytics software installed across engineering team.", rootCause: "Software installed via central deployment without proper license allocation.", resolution: "Licenses procured, deployment process updated to verify license availability" },
    { id: 20, title: "DDoS attack on customer-facing service", severity: "critical", status: "resolved", reportedDate: daysAgo(28), assignee: "Network Security", reportedBy: "DDoS Protection", category: "availability", description: "Layer 7 DDoS attack targeted customer authentication endpoint. WAF and DDoS protection mitigated impact with 2-minute latency spike.", rootCause: "Targeted attack on login endpoint, likely competitor or activist group.", resolution: "Attack mitigated by WAF rules, IPs blocked, post-incident review completed" },
    { id: 21, title: "Employee data access without business need", severity: "high", status: "remediation", reportedDate: daysAgo(12), assignee: "Privacy Officer", reportedBy: "Access Review", category: "unauthorized_access", description: "Quarterly access review identified manager accessing HR records of employees outside their reporting line without authorization.", rootCause: "Excessive access rights not removed after team restructuring.", resolution: "Access revoked, data access logs reviewed, HR system access controls updated" },
    { id: 22, title: "Certificate expiration causes outage", severity: "high", status: "resolved", reportedDate: daysAgo(40), assignee: "Infrastructure", reportedBy: "Monitoring Alert", category: "availability", description: "Expired TLS certificate caused 45-minute service outage for customer-facing API. Automated certificate renewal had failed silently.", rootCause: "Automated certificate renewal script had bug that caused silent failures for specific certificate type.", resolution: "Certificate manually renewed, renewal script fixed, monitoring added for certificate expiry" },
    { id: 23, title: "Confidential document left in public area", severity: "low", status: "closed", reportedDate: daysAgo(45), assignee: "Facilities", reportedBy: "Employee Report", category: "physical_security", description: "Confidential merger documents found in meeting room shared with external visitors. Documents contained non-public financial information.", rootCause: "Employee forgot to collect documents after meeting.", resolution: "Documents secured, employee reminded of clean desk policy" },
    { id: 24, title: "GDPR data portability request backlog", severity: "medium", status: "remediation", reportedDate: daysAgo(15), assignee: "Data Engineering", reportedBy: "DPO", category: "compliance_failure", description: "Data portability requests accumulated due to manually intensive export process requiring engineering support.", rootCause: "Lack of automated data export functionality for customer data.", resolution: "Automated export tool being developed, interim manual process documented" },
    { id: 25, title: "Customer account takeover attempt", severity: "critical", status: "investigating", reportedDate: daysAgo(1), assignee: "Security Team", reportedBy: "Fraud Detection", category: "account_compromise", description: "Multiple customer accounts showed login attempts from botnet IPs. Credential stuffing attack in progress.", rootCause: "", resolution: "" },
    { id: 26, title: "Unsecured API endpoint discovery", severity: "high", status: "resolved", reportedDate: daysAgo(33), assignee: "AppSec Team", reportedBy: "Pen Test", category: "vulnerability", description: "Penetration test discovered internal API endpoint accessible without authentication that returns user profile data.", rootCause: "API gateway routing misconfiguration allowed public access to internal endpoint.", resolution: "Endpoint secured, API gateway configuration audited, additional testing completed" },
    { id: 27, title: "Vendor contract termination - data return", severity: "medium", status: "closed", reportedDate: daysAgo(50), assignee: "Procurement", reportedBy: "Vendor Manager", category: "third_party", description: "Former vendor failed to return customer data within contractual 30-day window after contract termination.", rootCause: "Vendor operational delay and unclear data return process.", resolution: "Data received after escalation, vendor offboarding process updated" },
    { id: 28, title: "Biometric time clock data access concern", severity: "medium", status: "resolved", reportedDate: daysAgo(20), assignee: "Privacy Officer", reportedBy: "Employee Complaint", category: "privacy", description: "Employee raised concern about biometric fingerprint data collected for time tracking and who has access to it.", rootCause: "Lack of transparency about biometric data handling and access controls.", resolution: "Privacy notice updated, access controls reviewed, employee notified of data handling practices" },
    { id: 29, title: "Unauthorized software installation", severity: "low", status: "closed", reportedDate: daysAgo(55), assignee: "IT Operations", reportedBy: "Software Inventory", category: "policy_violation", description: "Employee installed unauthorized screen recording software on company laptop. Software had data exfiltration capabilities.", rootCause: "Employee wanted to record training sessions but used unapproved software.", resolution: "Software removed, approved alternatives provided, policy reminded" },
    { id: 30, title: "Executive impersonation - wire fraud attempt", severity: "critical", status: "resolved", reportedDate: daysAgo(42), assignee: "Treasury", reportedBy: "Accounts Payable", category: "fraud", description: "AP team received email appearing from CFO requesting urgent wire transfer of $250,000 to new vendor. Alert employee verified request verbally and stopped transfer.", rootCause: "Spear-phishing email spoofing CFO's email address with social engineering.", resolution: "Wire transfer blocked, security awareness team notified, training example created" },
  ];
}

export function getIncidentsSummary() {
  const incidents = getIncidents();
  return {
    total: incidents.length,
    byStatus: {
      reported: incidents.filter(i => i.status === "reported").length,
      investigating: incidents.filter(i => i.status === "investigating").length,
      remediation: incidents.filter(i => i.status === "remediation").length,
      resolved: incidents.filter(i => i.status === "resolved").length,
      closed: incidents.filter(i => i.status === "closed").length,
    },
    bySeverity: {
      critical: incidents.filter(i => i.severity === "critical").length,
      high: incidents.filter(i => i.severity === "high").length,
      medium: incidents.filter(i => i.severity === "medium").length,
      low: incidents.filter(i => i.severity === "low").length,
    },
    byCategory: {
      phishing: incidents.filter(i => i.category === "phishing").length,
      unauthorized_access: incidents.filter(i => i.category === "unauthorized_access").length,
      misconfiguration: incidents.filter(i => i.category === "misconfiguration").length,
      malware: incidents.filter(i => i.category === "malware").length,
      compliance_failure: incidents.filter(i => i.category === "compliance_failure").length,
      third_party: incidents.filter(i => i.category === "third_party").length,
      account_compromise: incidents.filter(i => i.category === "account_compromise").length,
      data_exfiltration: incidents.filter(i => i.category === "data_exfiltration").length,
      policy_violation: incidents.filter(i => i.category === "policy_violation").length,
      physical_security: incidents.filter(i => i.category === "physical_security").length,
    },
  };
}
